### ISSUE TITLE
`getLumberjackGridFieldConfig` should use `hasMethod` instead of `method_exists`

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-lumberjack#125]
I installed a module that uses Lumberjack. The module doesn't configure lumberjack's gridfield config, so I thought I write an Extension for that module's class and add the desired method `getLumberjackGridFieldConfig()` to it.

Unfortunately Lumberjack uses `if (method_exists($this->owner, 'getLumberjackGridFieldConfig'))` to check for custom config instead of Silverstripe's implementation `if $this->getOwner()->hasMethod('getLumberjackGridFieldConfig')` which also checks, if the method is callable or exists in an Extension to that object.

## PR
- https://github.com/silverstripe/silverstripe-lumberjack/pull/127

**Comment by michalkleiner** [comment]
That can be changed, a PR is always welcome :)

**Comment by wernerkrauss** [comment]
I just noticed, that e.g. `GridFieldConfig_RelationEditor` has the hook `$this->extend('updateConfig');` in its constructor. IMHO this should also be added to `GridFieldConfig_Lumberjack` when we're on it.

Of  course I can provide a PR

**Comment by GuySartorelli** [comment]
PR merged and tagged as [2.3.2](https://github.com/silverstripe/silverstripe-lumberjack/releases/tag/2.3.2) - it'll be tagged for the 3.x line after it's been merged up.

**Comment by emteknetnz** [comment]
This has been reverted as part of https://github.com/silverstripe/silverstripe-lumberjack/issues/128 and tagged as [2.3.3](https://github.com/silverstripe/silverstripe-lumberjack/releases/tag/2.3.3)
