### ISSUE TITLE
Lumbejack extended Page URL not hierarchical 

### ISSUE THREAD

**Issue by PatrickElsing** [silverstripe/silverstripe-lumberjack#14]
I have created a Page in SiteTree root named "Test".
As child Page on "Test" I create a Page named "Holder" extended with Lumberjack.
The url of "Holder" should looking like "/test/holder", but it is shown as "/holder".
Is it the purpose of Lumbjerjack to do so?

**Comment by CrashyBang** [comment]
:+1:

**Comment by micmania1** [comment]
I believe this has been fixed here: https://github.com/silverstripe/silverstripe-lumberjack/commit/be379a6c17632f424f49095fb901b083224f5a9d

Can you try and upgrade to that version and let me know if this fixes the issue?

**Comment by micmania1** [comment]
I'm going to close this as I haven't had any feedback. Please feel free to re-open if the problem persists.
