### ISSUE TITLE
Child page appears in SiteTree when opened from the Child Pages tab.

### ISSUE THREAD

**Issue by yawor** [silverstripe/silverstripe-lumberjack#30]
Hi,

I've noticed that when the child page is opened from the Child Pages tab/grid in Lumberjack extended page, the child page appears on the site tree view.

I have a NewsHolderPage which is extended with Lumberjack and a NewsPage which is the only allowed child of NewsHolderPage. I've added $show_in_sitetree = false to the NewsPage.

When I log into the admin panel (or refresh the whole page) everything looks OK. The NewsHolderPage doesn't show any children in the site tree view. But when I open the page, go to the Child Pages tab and open a NewsPage from there this page is added to the site tree as a child of NewsHolderPage. Each NewsPage I open from the grid is appended to the end of the children list in the site tree (so the order of the children is the order I've been opening the NewsPages.

For the children to disappear from the site tree I need to refresh the page.

Is there a way to prevent NewsPages being appended to the site tree on open?

**Comment by micmania1** [comment]
This is a known issue. See the following for a bit of a discussion on it: https://github.com/silverstripe/silverstripe-blog/issues/218

**Comment by micmania1** [comment]
FYI: I've noticed this issue exists in translatable too so this isn't a lumberjack only problem.

**Comment by dhensby** [comment]
It's more a framework issue, surely?

**Comment by tractorcow** [comment]
The issue at https://github.com/silverstripe/silverstripe-blog/issues/218 has since been closed, since it wasn't deemed significant enough a bug to remain open for an extended time without a fix.

If someone wants to change the behaviour they are welcome to submit a pull request, but in the mean time we aren't considering the status quo a problem.
