### ISSUE TITLE
Duplicate a child page

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-lumberjack#35]
Situation: an overview page lists events. The overview page could be a Lumberjack, listing all the events in a nice gridfield in the CMS. 

But one thing I'm missing then is that there is no button to duplicate an existing item. An event may be repeated, so only the date needs to be updated. 

There's a workaround by first opening the existing item, because then it appears in the SiteTree and you can duplicate it from there. But could there be any way to integrate this option into the gridfield?

**Comment by micmania1** [comment]
A duplicate GridField component should do the job but probably shouldn't be on by default otherwise the GridField will be too "busy". PR welcome :)

**Comment by tractorcow** [comment]
I wonder if "duplicate" could be an extra popup action when editing a page?

**Comment by dhensby** [comment]
We need a ContextMenuGridFieldComponent

**adds it to list**

**Comment by JorisDebonnet** [comment]
I would really really like to have this :) 

I'm happy to try and work on it, but am not sure where to start. If a Duplicate button is to be added right next to the Edit button in the GridField, that will need to be added in the framework, right? Perhaps even as a fully functional button, but disabled by default, and enabled in `GridFieldConfig_Lumberjack`? (or at least easily settable somehow)

**Comment by micmania1** [comment]
@JorisDebonnet you can see an example of custom GridField components here: https://github.com/silverstripe/silverstripe-lumberjack/blob/1.1/code/forms/gridfield/GridFieldSiteTreeAddNewButton.php You can also checkout the components in core to see how they're built (they basically implement interfaces).

And then you add the component here: https://github.com/silverstripe/silverstripe-lumberjack/blob/1.1/code/forms/gridfield/GridFieldConfig_Lumberjack.php

It would be preferential if we can re-use as much of the existing duplicate functionality/flow as possible. You can usually catch me on IRC if you have any questions or need help with this (feel free to email me too).

**Comment by dhensby** [comment]
could [copy-button](https://github.com/unisolutions/silverstripe-copybutton) module be of help? 

So many modules now its really hard to keep track

**Comment by tractorcow** [comment]
Yeah that would be a nice module to use. Lumberjack doesn't have to depend on that though, as long as it can be added.

Maybe document or add to composer suggest?

**Comment by dhensby** [comment]
see https://github.com/NobrainerWeb/Silverstripe-Content-Blocks/blob/master/code/ContentBlocksModule.php#L29-L31 for an example.

It would be nicer if copy-button had a decorator you could apply to models to add this component instead of having to hard hook like that, though.

**Comment by micmania1** [comment]
I'm going to close this as it doesn't seem to be moving anywhere. If somebody plans to work on it, please leave a comment and i'd be happy to re-open.
