### ISSUE TITLE
Split out GridFieldSiteTreeState to own module

### ISSUE THREAD

**Issue by sheadawson** [silverstripe/silverstripe-lumberjack#36]
Hi, I wonder if you would be interested in splitting out GridFieldSiteTreeState into it's own module. This would mean other modules that have Versioned DataObjects managed in GridFields can have the same, consistent UI for the publish status column. The blocks module is an example - https://github.com/sheadawson/silverstripe-blocks/pull/79

Let me know what you think. I'm happy to help make this happen :)

**Comment by tractorcow** [comment]
We are thinking of moving versioned (from core) into its own module. Maybe we could do it as a part of that?

We've already merged versioned extensions for gridfield into framework on master branch.

**Comment by sheadawson** [comment]
OK cool yeap I'm all for this being part of Versioned core/module, that'd be awesome.
