### ISSUE TITLE
summary_fields are not respected

### ISSUE THREAD

**Issue by anselmdk** [silverstripe/silverstripe-lumberjack#37]
I had to extend `Lumberjack` for it to work.

See example:

```php
class FeaturedPersonHolder_Lumberjack extends Lumberjack
{
    /**
     * Allowing summary fields in the grid field
     * @param FieldList $fields
     */
    public function updateCMSFields(FieldList $fields) {
        $pages = FeaturedPerson::get()->filter(array(
            'ParentID' => $this->owner->ID
        ));
        $gridField = new GridField(
            "ChildPages",
            $this->getLumberjackTitle(),
            $pages,
            $this->getLumberjackGridFieldConfig()
        );

        $tab = new Tab('ChildPages', $this->getLumberjackTitle(), $gridField);
        $fields->insertAfter($tab, 'Main');
    }
}
```

The main difference to `Lumberjack`'s `updateCMSFields` method is:

```php
$pages = SiteTree::get()->filter(array(
    'ParentID' => $this->owner->ID,
    'ClassName' => $excluded
));
```

It seems that calling `SiteTree` directly doesn't allow for displaying summary fields.

With above approach I was able to easily customize the gridfield, see screenshot.

![screenshot 2016-04-15 07 39 38](https://cloud.githubusercontent.com/assets/1316533/14552289/3c35ec8e-02dd-11e6-8a12-43e823c70db8.png)

**Comment by tractorcow** [comment]
Are your summary fields on your base class (SiteTree) or on your subclass of Page?

**Comment by anselmdk** [comment]
They are on the subclass of `Page`, `FeaturedPerson` in the example.

**Comment by anselmdk** [comment]
Here's an example:

```php
class FeaturedPerson extends Page
{
    private static $summary_fields = [
        'TinyImage' => 'Image',
        'Title' => 'Title',
        'getRelatedSubjectsString' => 'Subjects'
    ];
}

**Comment by tractorcow** [comment]
Ah, I guess the problem is that summary_fields are only pulled from the class queried by lumberjack, not subpages. This isn't really a bug, but rather a requirement of the gridfield API.

The solution you've used in your code is the correct one to target a list to a specific subclass of SiteTree.

**Comment by micmania1** [comment]
@anselmdk https://github.com/silverstripe/silverstripe-lumberjack/pull/11 - I believe this would fix your problem. @assertchris is busy with other things and i'm sure he wouldn't complain if you were to take over the PR?

**Comment by davejtoews** [comment]
If anyone's in this thread looking for solutions I just rolled up a module to deal with this problem, among others in such a way that I don't have to override the query for each child/parent pairing.

https://github.com/evanshunt/lumberjack-sort-and-summary
