### ISSUE TITLE
show_in_sitetree disables the GridField

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-lumberjack#39]
Hey guys,

I've just started using the blog module, and I was initially confused when the BlogPosts didn't show up in the SiteTree.

[Reading the docs](https://github.com/silverstripe/silverstripe-blog/blob/master/docs/en/configuring-blog-posts.md) I noticed the setting `show_in_sitetree` - great!

I wasn't expecting it to disable the GridField.

Can we have a second config setting called `show_in_gridfield` or something to control that behaviour separately if required?

I'd like to display blog posts in both places.

Recreates silverstripe/silverstripe-blog#393

Cheers,
Robbie

**Comment by tractorcow** [comment]
Sure, can you raise a pull request with this feature? It'll go into Lumberjack::getExcludedSiteTreeClassNames() as a new option.

**Comment by michalkleiner** [comment]
Pull request #47.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
