### ISSUE TITLE
Line endings are Windows style not Unix

### ISSUE THREAD

**Issue by SilbinaryWolf** [silverstripe/silverstripe-lumberjack#43]
Developers working with Windows systems are getting issues when we patch files due to the line endings being Windows-style and not Unix.

I figure now is the perfect time to fix this considering the master branch pretty much just changed every file over spaces/tabs.

**Comment by tractorcow** [comment]
Line endings are whatever you configure git to use. :)

When I check these files out locally they are linux format, not windows.

See http://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings for how to configure your env locally.
