### ISSUE TITLE
Default sort does not work

### ISSUE THREAD

**Issue by karwalbubble** [silverstripe/silverstripe-lumberjack#59]
Hey,
Was just wondering why gridfield created using lumberjack is not displaying columns in the default order setup(want to display latest page on top) in child page. Is it only me or someone else had similar issue? or am I missing something?
Thanks heaps..

**Comment by robbieaverill** [comment]
Hi @karwalbubble can you please provide some example code to demonstrate the problem you're having, as well as the version of SilverStripe and lumberjack that you're using?

**Comment by karwalbubble** [comment]
Hi, I am using **SS 3.1** and **lumberjack 1.1.0 stable** version. 
I have added `private static $default_sort = '"Created" DESC';` in my sub page class and using lumberjack in Parent page class as below:
`private static $extensions = array(
        'Lumberjack',
    );`
Also updated GridFieldConfig_Lumberjack just to display columns in gridfield and custom name to Add button as normal. Please see below function:
`public function getLumberjackGridFieldConfig() {
        $gridFieldConfig = GridFieldConfig_Lumberjack::create();
        $gridFieldConfig->getComponentByType('GridFieldAddNewButton')->setButtonName('Add');
        //Set custom column name
        $gridFieldColumns = $gridFieldConfig->getComponentByType('GridFieldDataColumns');
        $displayFields = array(
            'Title' => 'Title',
        );
        $gridFieldColumns->setDisplayFields($displayFields);
        return $gridFieldConfig;
    }`

**Comment by karwalbubble** [comment]
Also tried adding it in config.yml file as below:
```

LandingPage:
  extensions:
    - 'Lumberjack'

SubPage:
  default_sort: '"Created" DESC'
  show_in_sitetree: false
```

**Comment by robbieaverill** [comment]
@karwalbubble are you able to try updating your version of SilverStripe framework?

**Comment by robbieaverill** [comment]
I can't reproduce this on SilverStripe 3.6.0. Switching the `default_sort` parameter for BlogPost (in my example) reflects correctly in the GridField rendered by Lumberjack.

My suggestion would be to try and update your core version, and if this issue still persists then feel free to reopen this issue :)

**Comment by karwalbubble** [comment]
Thanks @robbieaverill , I will try and find out if I have an option to update silverstripe version. So is it confirmed that it won't work with 3.0 version? I tried using simple gridfield and default sorting is working fine there but not with lumberjack.

**Comment by karwalbubble** [comment]
Can you please try this on Custom Page instead of Blog as it works fine on Blog Posts at my side as well?

**Comment by robbieaverill** [comment]
OK, I can reproduce this with a custom page type.

It does make me wonder how sort order could be controlled since the lumberjack GridField allows you to have multiple page types as children - each could have a different sort order definition.

cc @micmania1

**Comment by karwalbubble** [comment]
@robbieaverill, Thanks for looking into this. Yes that makes sense that due to multiple page type usage in lumberjack does not able to find the default sort. Is there any way to define single page type to be displayed in lumberjack?

**Comment by micmania1** [comment]
@robbieaverill @karwalbubble you can provide your own list in 1.3 with whatever sort you like: https://github.com/silverstripe/silverstripe-lumberjack/blob/1/code/extensions/Lumberjack.php#L156

Hope that solves the problem.

**Comment by warslett** [comment]
I've had a go by digging around in the blog module to see what they do. This is what I've added to my lumberjack enabled class:
```
    /**
     * {@inheritdoc}
     */
    public function stageChildren($showAll = false)
    {
        $staged = parent::stageChildren($showAll);
        $dataQuery = $staged->dataQuery()
            ->sort('Created', 'DESC');
        $staged->setDataQuery($dataQuery);
        return $staged;
    }
```
Now the odd thing is that when I dump the query I can see that it has added the correct ORDER BY to the sql but in the grid field it still appears to be ordered by ID ascending. I wonder if something is modifiyng the datalist after my modification. I use precisely the same sort order on a dataquery that displays results on the front end and the results are ordered as expected.

**Comment by robbieaverill** [comment]
>When you look at a page of items (blog posts or otherwise) you want to be able to see the most recent item you created first in most situations.

I think you could raise a new feature request for this

**Comment by davejtoews** [comment]
I just rolled up a module for this which among other things applies the $default_sort_order for any parent child pairing where only one child type is allowed. Saves me from having to override it separately for each parent/child pairing https://github.com/evanshunt/lumberjack-sort-and-summary

**Comment by palomamtnez** [comment]
@davejtoews awesome. I have used it and it works like a charm.
Only thing is that I had to do some tweaks to make it ompatible with Silverstripe 3

**Comment by davejtoews** [comment]
@palomamtnez I just created an SS3 branch. If you're willing to submit a PR I can roll your tweaks into a separate version.
