### ISSUE TITLE
show_in_sitetree not used in SS 3.6.2

### ISSUE THREAD

**Issue by TheBnl** [silverstripe/silverstripe-lumberjack#65]
Hi all,

I noticed that, after updating to SS 3.6.2, that all the pages previously hidden are now visible.

**Comment by dhensby** [comment]
What version did you upgrade from?

**Comment by dhensby** [comment]
And did lumberjack upgrade too or stay the same?

**Comment by TheBnl** [comment]
I upgraded the following packages:
silverstripe/framework (3.6.1 => 3.6.2)
silverstripe/cms (3.6.1 => 3.6.2)
silverstripe/lumberjack (1.3.1 => 1.3.2)

And mustangostang/spyc (0.6.2) got added

**Comment by TheBnl** [comment]
Forgot to mention these packages:
silverstripe/siteconfig (3.6.1 => 3.6.2)
silverstripe/reports (3.6.1 => 3.6.2)
silverstripe/blog (2.4.6 => 2.4.8)

**Comment by dhensby** [comment]
hmm - there do appear to be some changes that shouldn't have made a patch release (https://github.com/silverstripe/silverstripe-lumberjack/compare/1.3.1...1.3.2)

I'll leave this to @robbieaverill and the team to look into

**Comment by TheBnl** [comment]
Thanks for looking into it! 👍

**Comment by robbieaverill** [comment]
Ah yep. I think we need https://github.com/silverstripe/silverstripe-lumberjack/commit/6f1b166d9989d215756a9a8d5c0104552484bda9 cherry picked into the 1.3 release line. We broke semver by changing the return type but that was a mistake, it shouldn't have changed. Will fix this shortly and tag a new version.

**Comment by robbieaverill** [comment]
Fixed in 1.3.3, sorry about that. https://github.com/silverstripe/silverstripe-lumberjack/compare/1.3.2...1.3.3

**Comment by TheBnl** [comment]
Thanks for this!! 👍

**Comment by camfindlay** [comment]
@robbieaverill could we get a patch release to https://gitlab.cwp.govt.nz/cwp/cwp-recipe-blog/blob/1.7.0/composer.json then please :) to fix up semver issue in blog recipe ^1.7

**Comment by robbieaverill** [comment]
@camfindlay we can't really do that without a full recipe release.

You can alias the new version of lumberjack as the old version to get the change while keeping it compatible with the recipe though - for example:

```
composer require silverstripe/lumberjack "1.3.3 as 1.3.2"
```

**Comment by camfindlay** [comment]
Did this every get rolled out in any of the more recent CWP minor or patch releases?

**Comment by robbieaverill** [comment]
@camfindlay yep, CWP 1.9.0 has this fix
