### ISSUE TITLE
Update Gridfield "State" icons styling to font versions

### ISSUE THREAD

**Issue by hdpero** [silverstripe/silverstripe-lumberjack#71]
Now "State" icons are looking like this:
![gridfield-lumberjack-state-icons-before](https://user-images.githubusercontent.com/13778690/34908741-ef7d8776-f894-11e7-9a9d-72f9cc14306f.png)

**Comment by hdpero** [comment]
Fixed solution is on #70 , and looks like this:
![gridfield-lumberjack-state-icons-after](https://user-images.githubusercontent.com/13778690/34909490-7b72a4de-f8a2-11e7-8897-4640ed1a2ea4.png)

**Comment by robbieaverill** [comment]
Fixed in #70
