### ISSUE TITLE
Strange layout on a page with two $allowed_children

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-lumberjack#72]
I'm on SS4.1-dev and installed latest master of Lumberjack (65d4a42).

I get a strange css/layout when I go to "child pages":

![grafik](https://user-images.githubusercontent.com/1043925/36977343-1b8525e0-2081-11e8-9cb4-1d31f459c963.png)

**Comment by robbieaverill** [comment]
Can you please share your implementation of lumberjack?

**Comment by wernerkrauss** [comment]
@robbieaverill of course, see https://github.com/wernerkrauss/demo-lumberjack-issue-72

To reproduce this issue:
* clone repo
* `composer install`
* create a "Aktuelles" Page
* enjoy the graphics.

I got this bug in Firefox, didn't test it in another browser. Maybe it's related to german translation?

**Comment by robbieaverill** [comment]
Ideal, thanks!
