### ISSUE TITLE
Hidden items appear in site tree until next refresh

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-lumberjack#76]
When saved and/or published child items that are configured to not show in the site tree are rendered within it until the site tree is re-rendered/the CMS is reloaded/the site is flushed.

For instance, using the following setttings ...
```
NewsPage:
  show_in_sitetree: true

NewsArticle:
  show_in_sitetree: false
```

... the site tree after editing and publishing 'Newest News Article' as well as 'Latest News Article' (in contrast, 'News Article No. 1' and Test News Article No. 2' were not modified):

![image](https://user-images.githubusercontent.com/14869519/37937785-99606e24-31b7-11e8-97d2-8c10eb82186f.png)

The same site tree after refreshing the entire CMS:

![image](https://user-images.githubusercontent.com/14869519/37937793-9d7267ec-31b7-11e8-9cbb-1709ff670d2f.png)

To reproduce on SilverStripe 3:

```
silverstripe/lumberjack                   1.3.3
silverstripe/framework                    3.6.5
silverstripe/cms                          3.6.5
```

To reproduce on SilverStripe 4:

```
silverstripe/lumberjack                   2.0.0-alpha1 
silverstripe/framework                    4.1.x-dev 9ed3cd4 
silverstripe/cms                          4.1.x-dev 7dea009 
```

**Comment by dhensby** [comment]
This has been raised before and was closed as an "intended feature" or, at least, useful enough not to fix

see:
- https://github.com/silverstripe/silverstripe-blog/issues/218
- https://github.com/silverstripe/silverstripe-lumberjack/issues/30

**Comment by raissanorth** [comment]
Alright then, it's a feature 😉. Fine by me. Thanks for linking to the prior discussion @dhensby.

**Comment by dhensby** [comment]
I do agree it'd be better without this "feature" but I'm also not sure how it's solvable right now
