### ISSUE TITLE
Lumberjack creates a tab for every inherited $this->extend('updateCMSFields', $fields);

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-lumberjack#78]
I'm having a serious issue where lumberjack is creating multiple duplicate tabs in the CMS.

Let's say the `Page` class has a `$this->extend('updateCMSFields', $fields);` in `getCMSFields()`, and page class `Blog` extends `Page` and also has a `$this->extend('updateCMSFields', $fields);` in `getCMSFields()`. `Blog` has lumberjack.

This is the result in SilverStripe 4:
![silverstripe - edit page](https://user-images.githubusercontent.com/1463435/38064418-5b0969a6-335a-11e8-90cf-bbda1d0d28a7.png)

How can this be avoided?

**Comment by robbieaverill** [comment]
@axllent can you share the actual code you're using?

You should only ever have one `$this->extend('updateCMSFields` extension point, and that generally is defined in SiteTree. If you're defining it in your own page's getCMSFields method you need to ensure that you're (A) not calling `parent::getCMSFields()` and (B) handling your own form scaffolding, since you're not using the parent's defaults.

If you define this extension point more than once you will have unwanted side effects.

**Comment by axllent** [comment]
Ahhh, that explains it @robbieaverill thank you - I was under the impression that it could be (and should be) defined at multiple points within extending classes. No need to share the code, you understand fully! BasicallyI was extending SiteTree classes with:

```
<?php
use SilverStripe\CMS\Model\SiteTree;
class Page extends SiteTree
{
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        ......
        $this->extend('updateCMSFields', $fields);
        return $fields;
    }
}
```

I've never had an issue (until now) and it took a while to work out wtf was causing it ;-) The downside of extending it from SiteTree though is it doesn't allow you to access the fields created in the extending classes as the `updateCMSFields()` is run against the SiteTree's `getCMSFields()`'s fields and not  the extending classes. I guess I could just use my own function, eg `$this->extend('updatePageCMSFields', $fields);` which seems like the best way to go.

**Comment by robbieaverill** [comment]
Yeah you could do that. Also keep in mind the order in which these extensions run, so for example it can often be a good idea to use `beforeUpdateCMSFields` callbacks in your pages, e.g.

```php
public function getCMSFields()
{
    $this->beforeUpdateCMSFields(function (FieldList $fields) {
        $fields->addFieldToTab('Root.Main', TextField::create('Example');
    });
    return parent::getCMSFields(); // updateCMSFields callbacks are run here, the callback above is run first
}
```

**Comment by axllent** [comment]
Thanks Robbie, your help & tips are appreciated!
