### ISSUE TITLE
Lumberjack doesn't work with `hide_from_cms_tree` setting

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-lumberjack#83]
In case a page has both `Lumberjack` and `hide_from_cms_tree` applied to it, the application breaks because `showingCMSTree()` is not available in Lumberjack. This is probably an edge case since you wouldn't want to have both these settings applied to the same page, still, it shouldn't break the application. One solution is to add `showingCMSTree()` to `SilverStripe\Lumberjack\ModelLumberjack`.

We are running on `2.x-dev` version.

**Comment by robbieaverill** [comment]
Fix at https://github.com/silverstripe/silverstripe-lumberjack/pull/84

**Comment by NightJar** [comment]
auto resolving isn't working for some reason. Closing because the PR is merged.

**Comment by robbieaverill** [comment]
GitHub auto closing only works when merging into the default branch for the repo (usually master)
